### PR TITLE
Add settings menu and image file format options

### LINKED ISSUE #52: Settings page
Make a settings page and config saving so user can choose things like output directory, file format, and whatever future thing could be appropriate for a settings dialog

### PR DESCRIPTION
**Pull request by Davidy22**
Resolves #52, opens the way for a pile of low hanging fruit

### CODE REVIEW

**Comment by dhananjaylatkar** [comment]
Screenshot 2021-08-10 at 11 31 25 PM
this looks bad. make closing bracket to appear right after last letter. too much padding is going on.

Also, image preview for PNG and TXT are not working

**Comment by dhananjaylatkar** [comment]
only jpg image preview is allowed.

See frames.py line no 177

**Comment by Davidy22** [comment]
Asciimatics dropdown just doesn't have the option, can send a patch upstream but this is what we're going to have. Enable other image formats was literally one line, text display'll be a seperate issue.

**Comment by Davidy22** [comment]
Merging because it won't happen if I don't do it

**Pull request merged**
